workspaces := ""

# Displays available recipes by running `just -l`.
setup:
  #!/usr/bin/env bash
  just -l

# Run the dev server
dev *args:
  #!/usr/bin/env bash
  run_cmd() {
    echo "$@" 
    "$@"
  }

  dev() {
    run_cmd bun run astro dev "$@"
  }

  if [ -z "{{args}}" ]; then
    dev
  else 
    dev "{{args}}"
  fi

deploy:
  bash scripts/publish.sh

# Install dependencies
i: 
  bun install

# Build TypeScript and then run vuepress build
b:
  bun run build

preview:
  bun run preview

# Compile TypeScript to JS.
tsc:
  tsc

fmt: 
  bun run format

lint:
  bun run lint:eslint
